- tests/dockerfile/test_runner.py
> fix docker test

- .github/workflows/pr-test.yml
- performance_tests/test_checkov_performance.py
> add performance test

- checkov/common/models/enums.py
- checkov/runner_filter.py
- checkov/sast/checks/base_check.py
- checkov/sast/checks/base_registry.py
- checkov/sast/runner.py
- performance_tests/test_checkov_performance.py
- tests/sast/test_runner.py
> feature(sast): skip checks

- checkov/sast/checks/java/DisabledCSRF.yaml
- checkov/sast/checks/java/ImproperAuthorization.yaml
- checkov/sast/checks/java/PublicDirectoryWrite.yaml
- tests/sast/source_code/java/DisabledCSRF/fail_1.java
- tests/sast/source_code/java/DisabledCSRF/fail_2.java
- tests/sast/source_code/java/DisabledCSRF/pass.java
- tests/sast/source_code/java/ImproperAuthorization/fail.java
- tests/sast/source_code/java/ImproperAuthorization/pass.java
- tests/sast/source_code/java/PublicDirectoryWrite/fail1.java
- tests/sast/source_code/java/PublicDirectoryWrite/fail2.java
- tests/sast/source_code/java/PublicDirectoryWrite/fail3.java
- tests/sast/source_code/java/PublicDirectoryWrite/pass1.java
- tests/sast/source_code/java/PublicDirectoryWrite/pass2.java
- tests/sast/test_checks.py
This PR adds new Java policies from OWASP
> feat(sast): New Java owasp policies

- .gitignore
- Pipfile.lock
- checkov/sast/common.py
- checkov/sast/go_runner.py
- checkov/sast/runner.py
- checkov/sast/semgrep_runner.py
- checkov/sast_core/Makefile
- checkov/sast_core/go.mod
- checkov/sast_core/go.sum
- checkov/sast_core/library.go
- tests/sast/test_go_runner.py
> feat(sast): create a go package and a runner, add a test to create to so

- .gitmodules
> add sast core as submodule

- checkov/cdk/checks/python/S3BucketEncryption.yaml
- checkov/cdk/checks/python/S3BucketKMSEncryption.yaml
- checkov/cdk/checks/python/S3BucketLogging.yaml
- checkov/cdk/checks/python/S3BucketPublicAccessBlock.yaml
- checkov/cdk/checks/python/S3BucketVersioning.yaml
- checkov/sast/checks_infra/base_registry.py
- checkov/sast/semgrep_runner.py
- tests/cdk/checks/conftest.py
- tests/cdk/checks/python/S3BucketEncryption/fail__2__.py
- tests/cdk/checks/python/S3BucketEncryption/pass.py
- tests/cdk/checks/python/S3BucketKMSEncryption/fail__3__.py
- tests/cdk/checks/python/S3BucketKMSEncryption/pass.py
- tests/cdk/checks/python/S3BucketLogging/fail.py
- tests/cdk/checks/python/S3BucketLogging/pass.py
- tests/cdk/checks/python/S3BucketPublicAccessBlock/fail.py
- tests/cdk/checks/python/S3BucketPublicAccessBlock/pass.py
- tests/cdk/checks/python/S3BucketVersioning/fail__2__.py
- tests/cdk/checks/python/S3BucketVersioning/pass.py
- tests/cdk/checks/test_checks_python.py
- tests/cdk/checks/utils.py
- tests/cdk/examples/s3.py
- tests/cdk/test_runner.py
- tests/sast/registry_tests/test_registry.py
> feat(general): add CDK Python checks

- checkov/sast/engines/prisma_engine.py
> feat(sast): add dylib support

- checkov/common/bridgecrew/integration_features/features/licensing_integration.py
- checkov/sast/engines/prisma_engine.py
- tests/common/integration_features/test_licensing_integration.py
> feat(sast): support alias arch

- checkov/sast/checks_infra/base_registry.py
- checkov/sast/engines/prisma_engine.py
> feat(sast): Add auth to payload

- checkov/sast/engines/prisma_engine.py
- checkov/sast/prisma_models/report.py
> chore: Added profiler data

- checkov/common/util/ext_argument_parser.py
- checkov/sast/prisma_models/report.py
> feat(sast): Fix Report Fields

- checkov/common/output/report.py
- checkov/sast/consts.py
- checkov/sast/engines/prisma_engine.py
- checkov/sast/prisma_models/report.py
- checkov/sast/report.py
> chore(sast): Fixed SAST auth and improved console output.

- .github/workflows/pr-test.yml
- checkov/sast/engines/prisma_engine.py
- checkov/sast/prisma_models/report.py
- checkov/sast/report.py
- sast_integration_tests/prepare_data.sh
- sast_integration_tests/run_integration_tests.sh
- sast_integration_tests/test_checkov_cli_integration_report.py
- sast_integration_tests/test_checkov_sast_report.py
1. Created a new pipeline for SAST integration tests using an API key. 
2. Did some changes in setting the SAST artifact - adjusted the regex to allow having `v` in the version + invalidate the locally found artifact to fetch a new one every day.
> chore(sast): SAST integration tests (excluding Windows)

- checkov/sast/engines/prisma_engine.py
> fix(sast): Fix print of codeblock

- checkov/common/output/record.py
- checkov/sast/common.py
- checkov/sast/engines/prisma_engine.py
- checkov/sast/engines/semgrep_engine.py
- checkov/sast/prisma_models/report.py
- checkov/sast/record.py
* Got Taint Mode data from prisma report.
* Implemented the multiline output with `...`
> chore(sast): Create output for Taint Mode

- checkov/sast/engines/prisma_engine.py
Passed to prisma engine the checks stated in runner filter.
> chore(sast): Support -c flag for SAST

- checkov/sast/common.py
- checkov/sast/engines/prisma_engine.py
- checkov/sast/prisma_models/report.py
Fixes # (issue)
*Include a description of what makes it a violation and any relevant external links.*
*How does someone fix the issue in code and/or in runtime?*
> chore(sast): Support multiline taint output

- checkov/sast/engines/prisma_engine.py
- checkov/sast/prisma_models/library_input.py
> chore(sast): skip check arg for sast

- checkov/sast/engines/prisma_engine.py
- checkov/sast/prisma_models/library_input.py
> chore(sast): add skip-path arg

- checkov/sast/prisma_models/report.py
- checkov/sast/report.py
- tests/common/integration_features/test_vulnerabilities_integration.py
> fix(sast): import report

- checkov/runner_filter.py
- tests/common/test_runner_filter.py
- tests/test_runner_filter.py
> chore(sast): all frameworks = all sast frameworks

- cdk_integration_tests/src/python/S3BlockPublicPolicy/fail__2__.py
- cdk_integration_tests/src/python/S3BlockPublicPolicy/pass.py
- cdk_integration_tests/src/python/S3IgnorePublicACLs/fail__2__.py
- cdk_integration_tests/src/python/S3IgnorePublicACLs/pass.py
- cdk_integration_tests/src/python/S3PublicACLRead/fail__3__.py
- cdk_integration_tests/src/python/S3PublicACLRead/pass.py
- cdk_integration_tests/src/python/SNSTopicEncryption/fail.py
- cdk_integration_tests/src/python/SNSTopicEncryption/pass.py
- cdk_integration_tests/test_checks_python.py
- checkov/cdk/checks/python/S3BlockPublicPolicy.yaml
- checkov/cdk/checks/python/S3IgnorePublicACLs.yaml
- checkov/cdk/checks/python/S3PublicACLRead.yaml
- checkov/cdk/checks/python/SNSTopicEncryption.yaml
> feat(cloudformation): Add cdk policies oct 23
